openapi: 3.0.1
info:
  title: Example API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /hello:
    get:
      summary: Greet
      operationId: getHello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
