name: Publish API to GitHub Packages
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - main
    paths:
      - 'openapi/**'
      - 'quarkus-server/**'
      - 'angular-client/**'
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Quarkus Server Stub
        working-directory: quarkus-server
        run: mvn clean compile -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular Client Dependencies
        working-directory: angular-client
        run: npm ci

      - name: Generate Angular API Client
        working-directory: angular-client
        run: npm run generate:api

  publish-java:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p $HOME/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">" > $HOME/.m2/settings.xml
          echo "  <servers>" >> $HOME/.m2/settings.xml
          echo "    <server>" >> $HOME/.m2/settings.xml
          echo "      <id>github</id>" >> $HOME/.m2/settings.xml
          echo "      <username>${{ github.actor }}</username>" >> $HOME/.m2/settings.xml
          echo "      <password>${{ secrets.GITHUB_TOKEN }}</password>" >> $HOME/.m2/settings.xml
          echo "    </server>" >> $HOME/.m2/settings.xml
          echo "  </servers>" >> $HOME/.m2/settings.xml
          echo "</settings>" >> $HOME/.m2/settings.xml

      - name: Deploy Quarkus server to GitHub Packages
        working-directory: quarkus-server
        run: mvn deploy -DskipTests

  publish-node:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js for npm publish
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@letsplay9'
          always-auth: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove private flag from package.json
        working-directory: angular-client
        run: sed -i '/"private"/d' package.json

      - name: Publish Angular client to GitHub Packages
        working-directory: angular-client
        run: npm publish --access public
