name: Publish API to GitHub Packages
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Generate Quarkus Server Stub
        working-directory: quarkus-server
        run: mvn clean compile -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular Client Dependencies
        working-directory: angular-client
        run: npm ci

      - name: Generate Angular API Client
        working-directory: angular-client
        run: npm run generate:api

      - name: Upload Quarkus artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-server
          path: quarkus-server/target

      - name: Upload Angular client
        uses: actions/upload-artifact@v4
        with:
          name: angular-client
          path: angular-client

  publish-java:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Quarkus artifact
        uses: actions/download-artifact@v4
        with:
          name: quarkus-server
          path: quarkus-server

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p $HOME/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">" > $HOME/.m2/settings.xml
          echo "  <servers>" >> $HOME/.m2/settings.xml
          echo "    <server>" >> $HOME/.m2/settings.xml
          echo "      <id>github</id>" >> $HOME/.m2/settings.xml
          echo "      <username>${{ github.actor }}</username>" >> $HOME/.m2/settings.xml
          echo "      <password>${{ secrets.GITHUB_TOKEN }}</password>" >> $HOME/.m2/settings.xml
          echo "    </server>" >> $HOME/.m2/settings.xml
          echo "  </servers>" >> $HOME/.m2/settings.xml
          echo "</settings>" >> $HOME/.m2/settings.xml

      - name: Deploy Quarkus server to GitHub Packages
        working-directory: quarkus-server
        run: mvn deploy -DskipTests \

  publish-node:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Download Angular client
        uses: actions/download-artifact@v4
        with:
          name: angular-client
          path: angular-client

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure npm for GitHub Packages
        working-directory: angular-client
        run: |
          echo "@letsplay9:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Debug npm configuration
        working-directory: angular-client
        run: |
          echo "== package.json =="
          cat package.json
          echo "== npm config list =="
          npm config list
          echo "== npm whoami =="
          npm whoami --registry https://npm.pkg.github.com || true

      - name: Remove private flag from package.json
        working-directory: angular-client
        run: sed -i '/"private"/d' package.json

      - name: Bump package version
        working-directory: angular-client
        run: npm version patch --no-git-tag-version

      - name: Publish Angular client to GitHub Packages
        working-directory: angular-client
        run: npm publish --access public

      - name: Commit bumped version
        working-directory: angular-client
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version after publish"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
