name: Publish API to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Quarkus server and Angular client
        run: |
          openapi-generator-cli generate -i openapi.yml -g java --library quarkus -o quarkus-server
          openapi-generator-cli generate -i openapi.yml -g typescript-angular -o angular-client
  publish-java:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Quarkus server to GitHub Packages
        working-directory: quarkus-server
        run: mvn deploy -DskipTests
  publish-node:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure npm auth
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Publish Angular client to GitHub Packages
        working-directory: angular-client
        run: npm publish
